spring.application.name=Scalable Url Shortener

server.port=${PORT:8080}

spring.mongodb.uri=mongodb+srv://vishalgulatinitj_db_user:7d83K8nOBLJPH5Fu@cluster0.pfckrb6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.redis.host=localhost
spring.redis.port=6379
