spring.application.name=Scalable Url Shortener

server.port=${PORT:8080}

spring.mongodb.uri=mongodb+srv://urlshortener:Vishal9760384814@cluster0.jftgck8.mongodb.net/urlshortener?retryWrites=true&w=majority

spring.redis.host=localhost
spring.redis.port=6379
